language: ruby
sudo: false
before_install: gem install bundler

bundler_args: --without development doc

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - jruby-9.0.5.0

matrix:
  fast_finish: true

branches:
  only:
    - master
